#spring:
#  datasource:
#    # 配置自带数据库的相对路径
#    url: jdbc:h2:~/.chat2db/db/chat2db_dev;FILE_LOCK=NO;MODE=MYSQL
#    driver-class-name: org.h2.Driver
# 端口号
server:
  port: 10821

chat2db:
  gateway:
    base-url: http://test.sqlgpt.cn/gateway
    model-base-url: http://test.sqlgpt.cn/gateway