import { DatabaseTypeCode } from '../common';

export default {
  type: DatabaseTypeCode.ORACLE,
  keywords: [
    'ACCESS',
    'ADD',
    'ALL',
    'ALTER',
    'AND',
    'ANY',
    'AS',
    'ASC',
    'AUDIT',
    'BETWEEN',
    'BY',
    'CHAR',
    'CHECK',
    'CLUSTER',
    'COLUMN',
    'COMMENT',
    'COMPRESS',
    'CONNECT',
    'CREATE',
    'CURRENT',
    'DATE',
    'DECIMAL',
    'DEFAULT',
    'DELETE',
    'DESC',
    'DISTINCT',
    'DROP',
    'ELSE',
    'EXCLUSIVE',
    'EXISTS',
    'FILE',
    'FLOAT',
    'FOR',
    'FROM',
    'GRANT',
    'GROUP',
    'HAVING',
    'IDENTIFIED',
    'IMMEDIATE',
    'IN',
    'INCREMENT',
    'INDEX',
    'INITIAL',
    'INSERT',
    'INTEGER',
    'INTERSECT',
    'INTO',
    'IS',
    'LEVEL',
    'LIKE',
    'LOCK',
    'LONG',
    'MAXEXTENTS',
    'MINUS',
    'MLSLABEL',
    'MODE',
    'MODIFY',
    'NOAUDIT',
    'NOCOMPRESS',
    'NOT',
    'NOWAIT',
    'NULL',
    'NUMBER',
    'OF',
    'OFFLINE',
    'ON',
    'ONLINE',
    'OPTION',
    'OR',
    'ORDER',
    'PCTFREE',
    'PRIOR',
    'PRIVILEGES',
    'PUBLIC',
    'RAW',
    'RENAME',
    'RESOURCE',
    'REVOKE',
    'ROW',
    'ROWID',
    'ROWNUM',
    'ROWS',
    'SELECT',
    'SESSION',
    'SET',
    'SHARE',
    'SIZE',
    'SMALLINT',
    'START',
    'SUCCESSFUL',
    'SYNONYM',
    'SYSDATE',
    'TABLE',
    'THEN',
    'TO',
    'TRIGGER',
    'UID',
    'UNION',
    'UNIQUE',
    'UPDATE',
    'USER',
    'VALIDATE',
    'VALUES',
    'VARCHAR',
    'VARCHAR2',
    'VIEW',
    'WHENEVER',
    'WHERE',
    'WITH',
  ],
  functions: [
    'CONNECT BY',
    'START WITH',
    'ORDER SIBLINGS BY',
    'SIBLINGS',
    'PRIOR',
    'NOCYCLE',
    'LEVEL',
    'GROUP BY',
    'GROUPING SETS',
    'CUBE',
    'ROLLUP',
    'PIVOT',
    'UNPIVOT',
    'MODEL',
    'DIMENSION',
    'MEASURES',
    'RULES',
    'ITERATE',
    'INCREMENT',
    'PRESENTV',
    'ABSENTV',
    'SQLQUERY',
    'ARRAY',
    'VARRAY',
    'ASSOCIATIVE ARRAY',
    'RECORD',
    'OBJECT',
    'TABLE',
    'VIEW',
    'MATERIALIZED VIEW',
    'CONTEXT',
    'DIRECTORY',
    'EDITION',
    'Profile',
    'ROLE',
    'SEQUENCE',
    'SYNONYM',
    'INDEXTYPE',
    'LIBRARY',
    'OPERATOR',
    'PROCEDURE',
    'FUNCTION',
    'PACKAGE',
    'TYPE',
    'TRIGGER',
    'LINK',
    'VIEW LOG',
    'CONSTRAINT',
    'CLUSTER',
    'COMMENT',
    'AUDIT',
    'NOAUDIT',
    'GRANT',
    'REVOKE',
    'FLASHBACK',
    'PURGE',
    'MERGE',
    'ALTER SESSION',
    'COMMIT',
    'ROLLBACK',
    'SAVEPOINT',
    'SET TRANSACTION',
    'LOCK',
    'ROW SHARE',
    'ROW EXCLUSIVE',
    'SHARE UPDATE',
    'SHARE',
    'EXCLUSIVE',
    'NOWAIT',
    'SKIP LOCKED',
    'PL/SQL',
    'AUTONOMOUS_TRANSACTION',
    'PRAGMA',
    'EXCEPTION',
    'SERIALLY_REUSABLE',
  ],
};
